services:
  app:
    build: .
    container_name: feed-app
    ports:
      - "${PORT}:${PORT}"  
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./public/uploads:/app/public/uploads

  mongo:
    image: mongo
    container_name: mongo
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: